### ISSUE TITLE
[Bug]: Quick Update and Auto Upgrade removes any ProductCode

### ISSUE THREAD

**Issue by OfficialEsco** [Trenly/winget-pkgs#123]
### Brief description of your issue

I just noticed YamlCreate version 2.0.2 keeps removing the ProductCode when using the Quick Update and Auto Upgrade function (non MSI ProductCodes)

### Steps to reproduce

```
Select Mode:

  [1] New Manifest or Package Version
  [2] Quick Update Package Version (Note: Must be used only when previous version's metadata is complete.)
  [3] Update Package Metadata
  [4] New Locale
  [5] Remove a manifest
  [Q] Any key to quit

Selection: 2

[Required] Enter the Package Identifier, in the following format <Publisher shortname.Application shortname>. For example: Microsoft.Excel
PackageIdentifier: Pidgin.Pidgin

[Required] Enter the version. for example: 1.33.7
Version: 2.14.8
Found Existing Version: 2.14.7
Installer Entry #1:

        Architecture: x86
        InstallerType: nullsoft
        Scope: machine


[Required] Enter the download url to the installer.
Url: https://sourceforge.net/projects/pidgin/files/Pidgin/2.14.8/pidgin-2.14.8-offline.exe/download
```

### Expected behavior

```
Installers:
- Architecture: x86
  InstallerUrl: https://sourceforge.net/projects/pidgin/files/Pidgin/2.14.8/pidgin-2.14.8-offline.exe/download
  InstallerSha256: B237DE10D4FE5D44EABE97A7640D2A74B4D722A7CB2376CF5DF2BE632EDA3F51
  ProductCode: 'Pidgin'
```

### Actual behavior

```
Installers:
- Architecture: x86
  InstallerUrl: https://sourceforge.net/projects/pidgin/files/Pidgin/2.14.8/pidgin-2.14.8-offline.exe/download
  InstallerSha256: B237DE10D4FE5D44EABE97A7640D2A74B4D722A7CB2376CF5DF2BE632EDA3F51
```

### Environment

```shell
# Created with YamlCreate.ps1 v2.0.2 $debug=QUSU.7-2-0
from upstream/master
```
