### ISSUE TITLE
Rare InstallerSwitches issue

### ISSUE THREAD

**Issue by OfficialEsco** [Trenly/winget-pkgs#53]
# Brief description of your issue

Some manifests are structured and preferred like this

```
InstallerSwitches:
  Silent: /silent
  SilentWithProgress: /runimmediately
- Architecture: x64
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera_gx/79.0.4143.60/win/Opera_GX_79.0.4143.60_Setup_x64.exe
  InstallerSha256: 3EC1816E7FADB207B14AB0327F0EE7AD94D015A863A04901658B79B4F3FC7FEB
  InstallerSwitches:
    Custom: /allusers=0 /launchbrowser=0 /setdefaultbrowser=0 /enable-installer-stats=0 /enable-stats=0
- Architecture: x64
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera_gx/79.0.4143.60/win/Opera_GX_79.0.4143.60_Setup_x64.exe
  InstallerSha256: 3EC1816E7FADB207B14AB0327F0EE7AD94D015A863A04901658B79B4F3FC7FEB
  InstallerSwitches:
    Custom: /allusers=1 /launchbrowser=0 /setdefaultbrowser=0 /enable-installer-stats=0 /enable-stats=0
```

# Steps to reproduce

YamlCreate option 2
1. PackageName: Opera.Opera
2. PackageVersion: 79.0.4143.66
3. PackageUrl: https://get.geo.opera.com/pub/opera/desktop/79.0.4143.66/win/Opera_79.0.4143.66_Setup_x64.exe
    PackageUrl: https://get.geo.opera.com/pub/opera/desktop/79.0.4143.66/win/Opera_79.0.4143.66_Setup.exe

# Expected behavior

```
InstallerSwitches:
  Silent: /silent
  SilentWithProgress: /runimmediately
- Architecture: x64
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera_gx/79.0.4143.60/win/Opera_GX_79.0.4143.60_Setup_x64.exe
  InstallerSha256: 3EC1816E7FADB207B14AB0327F0EE7AD94D015A863A04901658B79B4F3FC7FEB
  InstallerSwitches:
    Custom: /allusers=0 /launchbrowser=0 /setdefaultbrowser=0 /enable-installer-stats=0 /enable-stats=0
- Architecture: x64
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera_gx/79.0.4143.60/win/Opera_GX_79.0.4143.60_Setup_x64.exe
  InstallerSha256: 3EC1816E7FADB207B14AB0327F0EE7AD94D015A863A04901658B79B4F3FC7FEB
  InstallerSwitches:
    Custom: /allusers=1 /launchbrowser=0 /setdefaultbrowser=0 /enable-installer-stats=0 /enable-stats=0
```

# Actual behavior

```
InstallerSwitches:
  Silent: /silent
  SilentWithProgress: /runimmediately
- Architecture: x64
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/79.0.4143.66/win/Opera_79.0.4143.66_Setup_x64.exe
  InstallerSha256: 3EC1816E7FADB207B14AB0327F0EE7AD94D015A863A04901658B79B4F3FC7FEB
- Architecture: x64
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/79.0.4143.66/win/Opera_79.0.4143.66_Setup_x64.exe
  InstallerSha256: 3EC1816E7FADB207B14AB0327F0EE7AD94D015A863A04901658B79B4F3FC7FEB
```
